# Generated by Django 4.2.3 on 2023-08-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_choice', models.CharField(choices=[('Matinale', '7:00 - 14:00'), ('Après-midi', '14:30 - 23:59')], max_length=10)),
                ('session_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sessionrequest')),
            ],
        ),
    ]
