# Generated by Django 4.2.3 on 2023-08-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sessionqueue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionQueue',
        ),
    ]
