# Generated by Django 4.2.3 on 2023-08-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_sessionqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Active', 'Active'), ('Complète', 'Complète')], default='En attente', max_length=20),
        ),
    ]
