# Generated by Django 4.2.3 on 2023-08-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sessionrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
